[2023-03-18 10:07:10,695] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-03-02T06:00:00+00:00 [queued]>
[2023-03-18 10:07:10,752] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-03-02T06:00:00+00:00 [queued]>
[2023-03-18 10:07:10,755] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-18 10:07:10,762] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-18 10:07:10,765] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-18 10:07:10,830] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-03-02 06:00:00+00:00
[2023-03-18 10:07:10,852] {standard_task_runner.py:52} INFO - Started process 962 to run task
[2023-03-18 10:07:10,887] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_v3.0', 'download_dataset_task', 'backfill__2021-03-02T06:00:00+00:00', '--job-id', '151', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxs_1j9yw', '--error-file', '/tmp/tmpv713a53a']
[2023-03-18 10:07:10,893] {standard_task_runner.py:77} INFO - Job 151: Subtask download_dataset_task
[2023-03-18 10:07:11,125] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-03-02T06:00:00+00:00 [running]> on host 8cface6de844
[2023-03-18 10:07:11,379] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-03-18 10:07:11,464] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_v3.0
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-03-02T06:00:00+00:00
[2023-03-18 10:07:11,478] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-18 10:07:11,481] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-03.csv.gz > /opt/***/yellow_tripdata_2021-03.csv']
[2023-03-18 10:07:11,530] {subprocess.py:85} INFO - Output:
[2023-03-18 10:14:15,969] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-18 10:14:16,000] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 962. PIDs of all processes in the group: [970, 980, 962]
[2023-03-18 10:14:16,004] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 962
[2023-03-18 10:14:16,025] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-18 10:14:16,034] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2023-03-18 10:14:16,279] {process_utils.py:70} INFO - Process psutil.Process(pid=970, status='terminated', started='10:07:11') (970) terminated with exit code None
[2023-03-18 10:14:16,290] {process_utils.py:70} INFO - Process psutil.Process(pid=980, status='terminated', started='10:07:11') (980) terminated with exit code None
[2023-03-18 10:14:16,363] {process_utils.py:70} INFO - Process psutil.Process(pid=962, status='terminated', exitcode=0, started='10:07:10') (962) terminated with exit code 0
